"""empty message

Revision ID: 981446ac27f4
Revises: 41e352e46fc1
Create Date: 2026-04-17 19:16:06.231566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981446ac27f4'
down_revision = '41e352e46fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=40), nullable=False))
        batch_op.drop_column('lasttname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lasttname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
